name: Build PR
on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install
              run: yarn
            - name: build
              run: yarn run build
            - name: run localstack
              run: docker-compose up -d
            - name: test
              run: yarn test
